const group = {
  groupPermissions: {
    sendMedia: {
      photos: false,
      videos: false,
      files: false,
      music: false,
      voiceMessages: false,
      videoMessages: false,
      stickers: false,
      polls: false,
      embedLinks: false,
    },
    sendTextMessages: false,
    addUsers: false,
    pinMessages: false,
    changeChatInfo: false,
    downloadVideos: true,
    downloadVoiceMessages: true,
  },
  _id: "675dc02c6f76575654d39ecc",
  name: "Telegrammy",
  image: null,
  description: null,
  createdAt: "2024-12-14T17:16:39.848Z",
  groupType: "Private",
  ownerId: "1",
  groupSizeLimit: 200000,
  admins: [
    {
      permissions: {
        manageStories: {
          postStories: true,
          editStories: true,
          deleteStories: true,
        },
        remainAnonymous: false,
        changeGroupInfo: true,
        deleteMessages: true,
        banUsers: true,
        addUsers: true,
        inviteUsersViaLink: true,
        pinMessages: true,
        manageLiveStreams: true,
        addNewAdmins: true,
      },
      adminId: "1",
      joinedAt: "2024-12-14T17:53:01.580Z",
      leftAt: "2024-12-14T17:52:26.683Z",
      adminAt: "2024-12-14T17:48:34.695Z",
      superAdminId: "6745004bf8bf4b2ea3b60834",
      mute: false,
      muteUntil: null,
      customTitle: "Owner",
      _id: "675dc5fdcdaee9cb45778b8f",
      _doc: {},
    },
  ],
  pinnedMessages: [],
  members: [
    {
      permissions: {
        sendMedia: {
          photos: true,
          videos: true,
          files: true,
          music: true,
          voiceMessages: true,
          videoMessages: true,
          stickers: true,
          polls: true,
          embedLinks: true,
        },
        sendMessages: false,
        addUsers: true,
        pinMessages: true,
        changeChatInfo: false,
        downloadVideos: true,
        downloadVoiceMessages: true,
      },
      memberId: "2",
      joinedAt: "2024-12-19T21:32:52.484Z",
      leftAt: null,
      mute: false,
      muteUntil: null,
      _id: "676491a363724b2467ca6b2b",
      _doc: {},
    },
  ],
  leftMembers: [],
  __v: 13,
  chatId: "675dc02c6f76575654d39ecf",
};

const populatedGroup = {
  groupPermissions: {
    sendMedia: {
      photos: false,
      videos: false,
      files: false,
      music: false,
      voiceMessages: false,
      videoMessages: false,
      stickers: false,
      polls: false,
      embedLinks: false,
    },
    sendTextMessages: false,
    addUsers: false,
    pinMessages: false,
    changeChatInfo: false,
    downloadVideos: true,
    downloadVoiceMessages: true,
  },
  _id: "675dc02c6f76575654d39ecc",
  name: "Telegrammy",
  image: null,
  description: null,
  createdAt: "2024-12-14T17:16:39.848Z",
  groupType: "Private",
  ownerId: "1",
  groupSizeLimit: 200000,
  admins: [
    {
      permissions: {
        manageStories: {
          postStories: true,
          editStories: true,
          deleteStories: true,
        },
        remainAnonymous: false,
        changeGroupInfo: true,
        deleteMessages: true,
        banUsers: true,
        addUsers: true,
        inviteUsersViaLink: true,
        pinMessages: true,
        manageLiveStreams: true,
        addNewAdmins: true,
      },
      adminId: {
        _id: "1",
      },
      joinedAt: "2024-12-14T17:53:01.580Z",
      leftAt: "2024-12-14T17:52:26.683Z",
      adminAt: "2024-12-14T17:48:34.695Z",
      superAdminId: "6745004bf8bf4b2ea3b60834",
      mute: false,
      muteUntil: null,
      customTitle: "Owner",
      _id: "675dc5fdcdaee9cb45778b8f",
      _doc: {},
    },
  ],
  pinnedMessages: [],
  members: [
    {
      permissions: {
        sendMedia: {
          photos: true,
          videos: true,
          files: true,
          music: true,
          voiceMessages: true,
          videoMessages: true,
          stickers: true,
          polls: true,
          embedLinks: true,
        },
        sendMessages: false,
        addUsers: true,
        pinMessages: true,
        changeChatInfo: false,
        downloadVideos: true,
        downloadVoiceMessages: true,
      },
      memberId: {
        _id: "2",
      },
      joinedAt: "2024-12-19T21:32:52.484Z",
      leftAt: null,
      mute: false,
      muteUntil: null,
      _id: "676491a363724b2467ca6b2b",
      _doc: {},
    },
  ],
  leftMembers: [],
  __v: 13,
  chatId: "675dc02c6f76575654d39ecf",
};

const message = {
  chatId: "675dc02c6f76575654d39ecf",
  mediaUrl: "https://example.com",
  messageType: "video",
  _id: "1",
};

module.exports = {
  group,
  populatedGroup,
  message,
};
